import Footer from "@/components/footer";
import Header from "@/components/header";
import HeroSection from "@/components/HeroSection";
import { QuoteSection } from "@/components/QuoteSection";
import Quote from "@/components/Quote";
import Head from "next/head";
export default function Home() {

  return (

    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Random Quotes Generator</title>
        <meta name="description" content="Generated by Aarjav Jain using Next.js" />
        <link rel="icon" href='/Logo.png' />
      </Head>
      <Header />
      <main className="flex-grow">
        <HeroSection />
        <QuoteSection />
        <Quote />
      </main>
      <Footer />
    </div>
  );
}
